name: flutter_lndhub
description: A wrapper for seamlessly interacting with a LndHub BlueWallet server.
version: 0.1.0
homepage: https://github.com/o-compilador/flutter_lndhub

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3